Form project
Psiale/microverse-HTML_FORMS pull request #1
Opened 2019-10-24 17:27 UTC by Psiale

2019-10-25 20:33 UTC, suretrust requested changes
Hi, @Psiale and @Skyrul,

**Great job thus far guys! :raised_hands:** 

- [ ] Please see my comments to make some adjustments. 

- [ ] Also, the `Create an Intuit account` is supposed to be inside the form tag.

- [ ]  The `One account for everything Intuit.` statement and `Learn more` link are absent in your design.

`[Optional]` The form contents should align to the center as shown in the design you are cloning.

`[Optional]` You can add some text decoration on hover to the links `Legal`, `Privacy`, and `Security`.

**Kindly submit for another review once you've fixed these issues.**

_Happy coding!_ :tada:

2019-10-25 20:33 UTC, suretrust commented on .vscode/settings.json
> +}
This should not be in your repository.

2019-10-25 20:33 UTC, suretrust commented on index.html
> +    <title>Document</title>
`[Optional]` A more descriptive title won't hurt.

2019-10-25 20:33 UTC, suretrust commented on index.html
> +                src="https://img.icons8.com/material-outlined/24/000000/lock.png"
The `img` element must have an `alt` attribute. To understand why you can check this [article](https://dev.to/belhassen07/why-is-the-alt-attribute-so-important-for-images-c37).

2019-10-25 20:33 UTC, suretrust commented on index.html
> +                  ><input type="email" name="email" required />
The label `for` attribute must contain the input `id` value. For ecample:

`<label for="the-value">Foo</label>`
`<input id="the-value">`

Kindly adjust for all other `label` and `input` elements. You can check [this article on w3schools](https://www.w3schools.com/tags/att_label_for.asp) to see how it was formatted.

2019-10-25 20:33 UTC, suretrust commented on index.html
> +                  ><input type="tel" name="phone" />
Refer to the comment above.

2019-10-25 20:33 UTC, suretrust commented on index.html
> +                  ><input type="password" name="password" required />
Refer to the comment above.

2019-10-25 20:33 UTC, suretrust commented on index.html
> +                  ><input type="password" name="confirm" required />
Refer to the comment above.

2019-10-25 21:37 UTC, suretrust requested changes
Hi, @Psiale and @Skyrul,

Please check my comments, some of the other corrections are still in your code.

Also, please ensure to fix linter errors before submitting another review.

_Happy coding!_

2019-10-25 21:37 UTC, suretrust commented on index.html
> +                src="https://plugin.intuitcdn.net/identity-authn-core-ui/1.2.9/images/icon-whitelock@3x.png"
The `img` tag still does not have an `alt` attribute.

2019-10-25 21:37 UTC, suretrust commented on .vscode/settings.json
> +}
Could you remove this folder?

2019-10-25 22:08 UTC, ebukaume commented
## Changes Required! :stop_sign: 

Hi guys :wave: 

This project is almost done, believe me. I like the effort you guys have put in so far. Let's fix these issues:

- [ ] Let's make stickler checks **go green** like @suretrust requested earlier. 
_The error messages are quite explanatory_ . You below and you can see that you typed `input-form` instead of `.input-form` ( _The dot makes is a class, which is what you wanted. Without the dot, the system thinks it is a tag, which it isn't thus the error_ ).
https://github.com/Psiale/microverse-HTML_FORMS/blob/2827dbd698ac40e85523636f317dd2363fae8c71/css/style.css#L59-L63
**Please go through the other errors and fix them all**

-  [ ] Let's make your README descriptive and professional. You can refer to [this guide](https://github.com/othneildrew/Best-README-Template) for inspiration and tips.

**Kindly submit another code review request after fixing the above issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-10-26 09:45 UTC, KaushikShivam approved these changes
# Status: Project Approved! 🎉 

Hello, guys! 👋 
Good job on implementing changes required by the previous TSEs. Everything looks great!!

**Congratulations! You can merge this code to your master branch and move on to the next. All the best**

**If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**

Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

2019-10-28 15:19 UTC, merged